//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kularaki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.services = new HashSet<services>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Адрес { get; set; }
        public string Дом { get; set; }
    
        public virtual ICollection<services> services { get; set; }
    }
}
