//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kularaki.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DryCleaningEntities1 : DbContext
    {
        public DryCleaningEntities1()
            : base("name=DryCleaningEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<services> services { get; set; }
        public DbSet<Types> Types { get; set; }
        public DbSet<TypesOfServices> TypesOfServices { get; set; }
        public DbSet<Сomplexity> Сomplexity { get; set; }
    }
}
