//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kularaki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class services
    {
        public int Id { get; set; }
        public System.DateTime ДатаПриема { get; set; }
        public Nullable<System.DateTime> ДатаВозврата { get; set; }
        public Nullable<int> IdTypesOfServices { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdComplexity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypesOfServices TypesOfServices { get; set; }
        public virtual Сomplexity Сomplexity { get; set; }
    }
}
