//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kularaki.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesOfServices
    {
        public TypesOfServices()
        {
            this.services = new HashSet<services>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public decimal Стоимость { get; set; }
        public string Тип { get; set; }
        public Nullable<int> IdTypes { get; set; }
    
        public virtual ICollection<services> services { get; set; }
        public virtual Types Types { get; set; }
    }
}
